### ISSUE TITLE
MavenReference assembly not stable in size or contents when mixed with other MavenReferences

### ISSUE THREAD

**Issue by NightOwl888** [ikvmnet/ikvm-maven#17]
I am seeing a class disappear and the file size of `junit.vintage.engine.dll` change when it is combined with other MavenReference that are dependent or have shared transient dependencies. Reproducing is straightforward.

## Single MavenReference

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <MavenReference Include="org.junit.vintage:junit-vintage-engine" Version="5.9.1" Debug="true" />
  </ItemGroup>

</Project>
```

This outputs a 75KB `junit.vintage.engine.dll`, and it usually (but not always) contains the class `org.junit.vintage.engine.VintageTestEngine` as is included in the `.jar`. This class is setup to be loaded by the SPI, but doesn't load when it doesn't physically exist in the assembly.

## Two MavenReferences

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <MavenReference Include="org.junit.platform:junit-platform-engine" Version="1.9.1" Debug="true" />

    <MavenReference Include="org.junit.vintage:junit-vintage-engine" Version="5.9.1" Debug="true" />
  </ItemGroup>

</Project>
```

This generates a 106KB `junit.vintage.engine.dll` file that doesn't contain the class `org.junit.vintage.engine.VintageTestEngine`. I have double checked my `.m2` cache and there is only 1 version of the `.jar` present.

## Multiple MavenReferences

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <MavenReference Include="org.junit.jupiter:junit-jupiter" Version="5.9.1" Debug="true" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-api" Version="5.9.1" Debug="true" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-engine" Version="5.9.1" Debug="true" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-migrationsupport" Version="5.9.1" Debug="true" />
    <MavenReference Include="org.junit.jupiter:junit-jupiter-params" Version="5.9.1" Debug="true" />

    <MavenReference Include="org.junit.platform:junit-platform-commons" Version="1.9.1" Debug="true" />
    <MavenReference Include="org.junit.platform:junit-platform-engine" Version="1.9.1" Debug="true" />
    <MavenReference Include="org.junit.platform:junit-platform-launcher" Version="1.9.1" Debug="true" />
    <MavenReference Include="org.junit.platform:junit-platform-reporting" Version="1.9.1" Debug="true" />
    <MavenReference Include="org.junit.platform:junit-platform-runner" Version="1.9.1" Debug="true" />
    
    <MavenReference Include="org.junit.vintage:junit-vintage-engine" Version="5.9.1" Debug="true" />
  </ItemGroup>

</Project>
```

This generates a 105KB `junit.vintage.engine.dll` file that doesn't contain the class `org.junit.vintage.engine.VintageTestEngine`.

**Comment by NightOwl888** [comment]
I have ruled out this having anything to do with the `Debug` setting and confirmed the issue also happens on `netcoreapp3.1`. I also tried rebooting my machine and nuking the ikvm cache to no avail.

There are 2 features that JUnit5 uses that I haven't used with any other project that are suspect:

1. The project is using a [Maven Bill of Materials](https://reflectoring.io/maven-bom/) to prevent version conflicts.
2. The project is using [Multi-Release JAR Files](https://www.baeldung.com/java-multi-release-jar) to compile for both JavaSE 8 and JavaSE 9.

Given the fact that there are some warnings in the build log about it not being able to compile some of the files below `META-INF/versions/9`, I suspect that the Multi-Release feature is most likely a contributor to the issue. If a file exists in the `META-INF/versions/9` folder that *will* compile under JavaSE 8, it may actually replace or destroy the output of that class that was intended for JavaSE 8.

```console
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : IKVM.NET Compiler (8.2.2-prerelease.8+Branch.develop.Sha.c9eb71a11321fec04be819c47ba2c009d418be41)
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : Copyright c 2022 Jeroen Frijters, Windward Studios, Jerome Haltom, Shad Storhaug
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning :
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0101: Unable to compile class "META-INF.versions.9.org.junit.platform.commons.util.ModuleUtils$ModuleReferenceScanner"
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning :     (class format error "META-INF.versions.9.org.junit.platform.commons.util.ModuleUtils$ModuleReferenceScanner (53.0)")
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0101: Unable to compile class "META-INF.versions.9.org.junit.platform.commons.util.ModuleUtils"
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning :     (class format error "META-INF.versions.9.org.junit.platform.commons.util.ModuleUtils (53.0)")
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0101: Unable to compile class "module-info"
1>F:\Users\shad\.nuget\packages\ikvm\8.2.2-prerelease0008\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning :     (class format error "module-info (53.0)")
```

I will attempt to `ikvmc` the packages so the options to exclude the appropriate `.class` files can be applied to test this theory.

Did the JDK 8 have to be changed in order to accommodate multi-release JARs? Answering this question would be helpful. If so, maybe it was patched in a higher version than 8u45-b14. If not, we may need to patch IKVM to ignore these files, since we cannot use it to compile JavaSE 9 or higher `.class` files, anyway.

**Comment by wasabii** [comment]
No. JDK 8 code was never supposed to process files inside of META-INF to begin with, which is why the MR stuff was added in there. It is a bug in ikvmc (and possibly other areas) that these files are even encountered.

**Comment by NightOwl888** [comment]
This issue has at least 2 contributors:

1. The `ikvmc` tool is adding the `.class` files from the META-INF directory into the build, and Java SE 8 tools should ignore these. This is being addressed by https://github.com/ikvm-revived/ikvm/pull/180 (currently a WIP).
2. Using the dependency graph directly from Maven doesn't function completely as a dependency graph for .NET assembly references. This was previously reported in #2, and will be discussed further there.

The `ikvmc` tool is also adding the `meta-info.class` files into the build, and Java SE 8 tools should ignore these. This is being addressed by https://github.com/ikvm-revived/ikvm/pull/180, as well. While it is not clear at this point that it is actually contributing to the problem, it produces warnings that Java SE 8 tools would not produce.

**Comment by wasabii** [comment]
Assuming this is closed. The issue mentioned initially is normal: some dependencies are optional, if they get included, the final output might change. Maven might unify versions, causing changes, as well.
