### ISSUE TITLE
Conversion fails if any Maven dependency contains version component bigger than 65535

### ISSUE THREAD

**Issue by aleksei-oecd** [ikvmnet/ikvm-maven#19]
Might be related to https://github.com/ikvm-revived/ikvm-maven/issues/16

My maven package conversion fails because of this dependency. 
 
```xml
<dependency>
    <groupId>net.java.dev.stax-utils</groupId>
    <artifactId>stax-utils</artifactId>
    <version>20070216</version>
</dependency>
```

The jar package version is bigger than [UInt16](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.version?redirectedfrom=MSDN&view=net-6.0#remarks) and this is a show stopper. Is it possible somehow to override the generated assembly version to avoid this problem?

**Comment by wasabii** [comment]
IKVM doesn't use the Maven version for anything, so this isn't likelya problem. What's your actual error?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Aleksei Arhipov ***@***.***>
Sent: Wednesday, November 2, 2022 12:31:46 PM
To: ikvm-revived/ikvm-maven ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ikvm-revived/ikvm-maven] Conversion fails if any Mavan dependency contains version segment bigger than 65535 (Issue #19)


Might be related to #16<https://github.com/ikvm-revived/ikvm-maven/issues/16>

My maven package conversion fails because of this dependency.

<dependency>
    <groupId>net.java.dev.stax-utils</groupId>
    <artifactId>stax-utils</artifactId>
    <version>20070216</version>
</dependency>

The jar package version is bigger than UInt16<https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.version?redirectedfrom=MSDN&view=net-6.0#remarks> and this is a show stopper. Is it possible somehow to override the generated assembly version to avoid this problem?

**Comment by aleksei-oecd** [comment]
```xml
<ItemGroup>
    <PackageReference Include="IKVM" Version="8.2.3" />
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
    <MavenReference Include="org.open-eid.cdoc4j:cdoc4j">
        <groupId>org.open-eid.cdoc4j</groupId>
        <artifactId>cdoc4j</artifactId>
        <version>1.4</version>
    </MavenReference>
</ItemGroup>
```
fails with this error

```
.nuget\packages\ikvm\8.2.3\buildTransitive\netstandard2.0\IKVM.targets(46,9): error IKVMSDK0004: The IkvmReference maven$net.java.dev.stax-utils:stax-utils:20070216 has invalid AssemblyName 'stax.utils' or AssemblyVersion '20070216.0'.
```

**Comment by wasabii** [comment]
Okay. So not the Maven version. The automatic module name version. Hmmm.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wasabii** [comment]
So the problem here is we need to find some stable/deterministic pattern for manufacturing an AssemblyVersion out of this. There are workarounds, that you can use, locally. But they require overriding MSBuild targets.

https://github.com/ikvm-revived/ikvm-maven/issues/16#issuecomment-1261305084

**Comment by aleksei-oecd** [comment]
yes, I think it's a nice workaround. With slight modification it worked out, will create a pull request for the documentation change to help others avoid the same issue. Meanwhile, encountered new problems, although all modules are built for Java 8. 

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="IKVM" Version="8.2.3" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.2" />
        <MavenReference Include="org.open-eid.cdoc4j:cdoc4j">
            <groupId>org.open-eid.cdoc4j</groupId>
            <artifactId>cdoc4j</artifactId>
            <version>1.4</version>
        </MavenReference>
    </ItemGroup>
    <Target Name="FixIkvmReference" AfterTargets="_GetMavenIkvmReferenceItems">
        <Message Importance="high" Text="$(IkvmMavenSdkDir)" />
        <ItemGroup>
            <IkvmReferenceItem Condition="'%(Identity)'=='maven$net.java.dev.stax-utils:stax-utils:20070216'">
                <AssemblyVersion>1.0.0.0</AssemblyVersion>
            </IkvmReferenceItem>
        </ItemGroup>
    </Target>
</Project>
```
a lot of warnings from org.bouncycastle.* modules that Class ... not found:

```
.nuget\packages\ikvm\8.2.3\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0100: Class "org.bouncycastle.asn1.ASN1Object" not found
.nuget\packages\ikvm\8.2.3\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0100: Class "org.bouncycastle.asn1.DERBitString" not found
.nuget\packages\ikvm\8.2.3\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0100: Class "org.bouncycastle.asn1.ASN1Integer" not found
.nuget\packages\ikvm\8.2.3\buildTransitive\netstandard2.0\IKVM.targets(100,9): warning : warning IKVMC0100: Class "org.bouncycastle.asn1.DEROctetString" not found
...
```

Will test if result .net libs are affected by these missing classes during conversion.
