### ISSUE TITLE
Casting issue due to duplicate assemblies generated/pulled

### ISSUE THREAD

**Issue by toddmcintosh** [ikvmnet/ikvm-maven#30]
I'm getting a conflict which seems to indicate Maven is generating 2 references to the Fop library, and I'm getting an error when it seems to be casting the same type in one ref to the type in the second ref. How do I prevent this?

Using:
IKVM.Maven.Sdk 1.4.1
Visual Studio 2022
.NET Core 6.0 Project

Error Text:
System.InvalidCastException: 

'[A]org.apache.fop.apps.FopFactory cannot be cast to [B]org.apache.fop.apps.FopFactory. 

Type A originates from 'fop.core-ikvm-runtime-injected, Version=2023.217.1124.45419, Culture=neutral, PublicKeyToken=null' in the context 'Default' in a byte array. 

Type B originates from 'fop, Version=2.7.0.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58' in the context 'Default' at location 'proj_dir\bin\Debug\net6.0\fop.dll'.'

**Comment by wasabii** [comment]
Can you provide a sample project for this by chance?

I was unable to find it happening.

**Comment by wasabii** [comment]
This is stale at this point. Reopen if the issue still exists.
