### ISSUE TITLE
Could not find artifact com.bugsnag:bugsnag-android:pom:5.+ in central

### ISSUE THREAD

**Issue by joshbartley** [ikvmnet/ikvm-maven#40]
Attempting to use the `com.github.team-telnyx:telnyx-webrtc-android` package and am getting an error about `Could not find artifact com.bugsnag:bugsnag-android:pom:5.+ in central (https://repo1.maven.org/maven2/)` and `Could not find artifact com.bugsnag:bugsnag-android:pom:5.+ in sumsub (https://maven.google.com/)`. 

I put in a request to the package to update `volley` to at least `1.2.0` which should fix the other issue just stuck on why bugsnag would be causing an issue as I can see it exists as a package.

Current project file.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-android</TargetFramework>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <MavenAdditionalRepositories>sumsub=https://jitpack.io</MavenAdditionalRepositories>
    <MavenAdditionalRepositories>sumsub=https://maven.google.com/</MavenAdditionalRepositories>
  </PropertyGroup> 

  <ItemGroup>
    <MavenReference Include="com.github.team-telnyx:telnyx-webrtc-android" Version="1.2.7" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.6.1" />
  </ItemGroup>
</Project>
```

**Comment by wasabii** [comment]
Property group replaces the content. Not appends.

**Comment by wasabii** [comment]
Ya know, coming back to this, yeah, you're not adding jitpack.io, since you're overwriting it with maven.google.com.....

But, because I was curious, I took a look at what these packages were. They don't even appear to be Java.

**Comment by joshbartley** [comment]
Ah, it must have the initial package cached then. The telnyx package is on jitpack and from the build looks like it can find the dependencies.

This is the source for the maven reference package. Looking at their repo it looks to be java. Not sure how it looks in the package as I'm not as familiar with Java as I am .net

https://github.com/team-telnyx/telnyx-webrtc-android

**Comment by wasabii** [comment]
That's an Android library. Which may be written in the Java language. But the artifact they produce and upload to Maven is NOT Java. There is no JAR file, only an AAR file.

**Comment by joshbartley** [comment]
I was able to grab the AAR and put it directly in the xamarin project and it seems to work instead of pulling all the dependencies this way. This might have been a false alarm with me trying something out new for the first time. Thanks for looking into this!

**Comment by wasabii** [comment]
I would be confused why you would need IKVM to use Java libraries inside Xamarin. Okay.

**Comment by joshbartley** [comment]
I think I ran across a reddit post about maven support in .net projects and then I just tried to fix the errors not realizing it was all tied to IKVM after it would download everything which is my bad.
