### ISSUE TITLE
IKVM.maven build crashing without any error and no information

### ISSUE THREAD

**Issue by HackPoint** [ikvmnet/ikvm-maven#41]
Hi @wasabii ,

I'm trying to build with maven my application built on top of `Calcite` and with usage of IKVM,
Seems like the build not passing and not showing any errors.
[CalciteIKVM.zip](https://github.com/ikvmnet/ikvm-maven/files/13268993/CalciteIKVM.zip)

As you can see in the picture the assemblies aren't being built.        
![image](https://github.com/ikvmnet/ikvm-maven/assets/6758579/69ac2dc3-3b92-43f8-8efb-991f3f4ecacc)

For example I kept only one dependency of `calcite-file`  but actually I have a list of them.
``` 
   <ItemGroup>
        <PackageReference Include="IKVM" Version="8.7.1" />
        <PackageReference Include="IKVM.Maven.Sdk" Version="1.6.1" />
    </ItemGroup>
    <ItemGroup>
        <MavenReference Include="org.apache.calcite:calcite-core" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite:calcite-server" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite:calcite-csv" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite:calcite-elasticsearch" Version="1.34.0" />
        <MavenReference Include="org.apache.calcite.avatica:avatica-server" Version="1.23.0" />
    </ItemGroup>
```

**Comment by wasabii** [comment]
I actually am receiving an error though:

1>C:\Users\jhaltom\.nuget\packages\ikvm.maven.sdk\1.6.0\buildTransitive\IKVM.Maven.Sdk.targets(96,9): error : ArtifactNotFoundException: Could not find artifact javax.jms:jms:jar:1.1 in central (https://repo1.maven.org/maven2/), try downloading from http://java.sun.com/products/jms/docs.html

**Comment by wasabii** [comment]
Since I already opened #39, I'm going to close this in favor of it.
