### ISSUE TITLE
Build fails on macOS arm64 with net472 target

### ISSUE THREAD

**Issue by paulirwin** [ikvmnet/ikvm-maven#49]
Working on testing https://github.com/apache/lucenenet/pull/892 with @NightOwl888, and I cannot build a project that targets net472 on macOS arm64 that uses MavenReference.

While that PR branch reproduces it, it is quite large, so here is a minimal reproduction.

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Bug</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.6.7" />
  </ItemGroup>
  
  <ItemGroup>
    <MavenReference Include="org.apache.opennlp:opennlp-tools" Version="1.9.4" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="en-sent.bin">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

(Note that the en-sent.bin bit is only needed if you want to actually run this example to see it working on a different target like .NET 6+. Get the file from [OpenNLP](https://opennlp.sourceforge.net/models-1.5/) and put in directory.)

```c#
using System;
using opennlp.tools.sentdetect;

namespace Bug
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using var modelIn = new java.io.FileInputStream("en-sent.bin");

            var model = new SentenceModel(modelIn);
            var sentenceDetector = new SentenceDetectorME(model);

            var sentences = sentenceDetector.sentDetect("  First sentence. Second sentence. ");
            Console.WriteLine(string.Join(";", sentences));
        }
    }
}
```

I have put this in a [gist](https://gist.github.com/paulirwin/08c9d11d155d597e329857e7448d4e25) if it is easier to clone it.

The build output is (paths replaced with $HOME):
```
$HOME/.nuget/packages/ikvm/8.7.3/buildTransitive/IKVM.Tasks.targets(31,9): error MSB4018: The "IkvmCompiler" task failed unexpectedly. [$HOME/git/ikvm-maven-reference-bug/ikvm-maven-reference-bug.csproj]
$HOME/.nuget/packages/ikvm/8.7.3/buildTransitive/IKVM.Tasks.targets(31,9): error MSB4018: IKVM.MSBuild.Tasks.IkvmTaskException: Missing tool path: '$HOME/.nuget/packages/ikvm.msbuild.tools.runtime.osx-arm64/8.7.3/buildTransitive/../ikvmc/net472/osx-arm64/'. [$HOME/git/ikvm-maven-reference-bug/ikvm-maven-reference-bug.csproj]
$HOME/.nuget/packages/ikvm/8.7.3/buildTransitive/IKVM.Tasks.targets(31,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmToolExecTask.Execute() in /_/src/IKVM.MSBuild.Tasks/IkvmToolExecTask.cs:line 79 [$HOME/git/ikvm-maven-reference-bug/ikvm-maven-reference-bug.csproj]
$HOME/.nuget/packages/ikvm/8.7.3/buildTransitive/IKVM.Tasks.targets(31,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmCompiler.Execute() in /_/src/IKVM.MSBuild.Tasks/IkvmCompiler.cs:line 239 [$HOME/git/ikvm-maven-reference-bug/ikvm-maven-reference-bug.csproj]
$HOME/.nuget/packages/ikvm/8.7.3/buildTransitive/IKVM.Tasks.targets(31,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [$HOME/git/ikvm-maven-reference-bug/ikvm-maven-reference-bug.csproj]
$HOME/.nuget/packages/ikvm/8.7.3/buildTransitive/IKVM.Tasks.targets(31,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [$HOME/git/ikvm-maven-reference-bug/ikvm-maven-reference-bug.csproj]
    0 Warning(s)
    1 Error(s)
```

Note that the use case here is not to be able to run .NET Framework 4.7.2 code on macOS arm64, but merely to build.

**Comment by wasabii** [comment]
Yeah. We do not have the ability to run builds targeting NetFX without having NetFX.

It's on the list.

**Comment by NightOwl888** [comment]
Just FYI, I was able to do the build on a macOS x64 build agent, but it doesn't work on arm64. Our project includes a private reference to [`Microsoft.NETFramework.ReferenceAssemblies`](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies) so the bits to build exist on the build machine.

**Comment by wasabii** [comment]
But since IKVM requires a framework version of ikvmc to build for framework....

**Comment by paulirwin** [comment]
How is that working on macOS x64? Just curious.

**Comment by wasabii** [comment]
I'm actually not sure either. Technically it should try to run the framework version of ikvmc..... Which if you have mono installed would try to load it. But then probably fail because it's mono

**Comment by NightOwl888** [comment]
So what is "officially" supported for building NetFX? Windows only? At present we are doing official builds on Windows x64, so that is fine.

But to merge the pull request, we need to get around the issue with contributors being able to build from source who may be using various platforms to do the build. We can conditionally exclude the net472 target in order for people to contribute, but should the condition be on ARM64 or should we just assume it doesn't work if they are not on Windows?

**Comment by wasabii** [comment]
The Framework ikvmc.exe executable can't run unless Framework is available. So, that means Windows (or Wine or working Mono or something). So, mostly, you can't run that except on Windows.

And the Framework ikvmc.exe is required to produce Framework assemblies.

So, you can only produce Framework assemblies on Windows.

The stuff I'm doing now is getting us closer (fixing up IKVM.Reflection, etc).

**Comment by wasabii** [comment]
I think there's only one major issue remaining though, in develop, which is that the determination of what counts as the "core lib" is hard coded. The corelib being one of "mscorlib", "System.Runtime" or "netstandard". Basically it needs to know what assembly to look in for System.Object and all that.

With the SRME stuff, we're going to be capable of emitting Framework executables targeting any platform (ARM64, etc) using the Core executable. So, that means the ARM64 Core version of ikvmc will be able to run on OSX and produce Framework executables.

Once it's able to do that, I'm going to have to reevaluate the MSBuild scripts. Right now they determine which IkvmTool to run based on the framework/runtime target and current OS version. That'll need to be changed. Probably to run using the tool corresponding with the current SDK environment (Core SDK or Framework), and ignore the target environment. And then communicate the corelib name to the tool somehow.

**Comment by wasabii** [comment]
This actually should work now if you have Mono installed. With proceeds on getting the Core executable running. But the Framework one did, with mono. So it's doable.
