### ISSUE TITLE
support for spring cli / initializr website or as dotnet new IKVM template

### ISSUE THREAD

**Issue by jkone27** [ikvmnet/ikvm-maven#55]
https://start.spring.io/

would be nice to have a dotnet tool like dotnet-ikvm-initializr that could init projects specifying maven dependencies from official or unofficial sources, and build the .NET solution

* https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new

 * https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html (official CLI) (a custom public server url can also be passed in)

**Comment by wasabii** [comment]
Neat idea. Probably would be separate from IKVM and IKVM maven though. A separate spring CLI tool. With a new template.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: jkone27 ***@***.***>
Sent: Monday, February 26, 2024 11:05:22 AM
To: ikvmnet/ikvm-maven ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ikvmnet/ikvm-maven] support for spring cli / initializr website or as dotnet new IKVM template (Issue #55)


https://start.spring.io/

would be nice to have a dotnet tool like dotnet-ikvm-initializr that could init projects specifying maven dependencies from official or unofficial sources, and build the .NET solution

  *   https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new

  *   https://docs.spring.io/spring-boot/docs/current/reference/html/cli.html (official CLI) (a custom public server url can also be passed in)

**Comment by wasabii** [comment]
Going to move this to a discussion.
