### ISSUE TITLE
Allow specifying cacerts or mscapi

### ISSUE THREAD

**Issue by superstrom** [ikvmnet/ikvm-maven#63]
I have my java dependencies in a local nexus repository that uses a local certificate trust chain for https.

I get a handshake_failure when `<MavenReference>` tries collecting dependencies.

Is there a way to specify a property set, to enable using a custom cacerts or mscapi when fetching items via `<MavenReference>`? 
(mscapi being preferred)

I do not have maven working separately in this environment, so I don't have a separate m2 settings file.

**Comment by wasabii** [comment]
Well, we pull in .m2/settings.xml as we should.... I think any customizations to the process would have to be there. But I'm not sure about the cert thing. Because I believe we already do mscapi.

**Comment by superstrom** [comment]
I've used `-Djavax.net.ssl.trustStoreProvider="SunMSCAPI" -Djavax.net.ssl.trustStoreType="Windows-ROOT"` in the past to get various java things to use mscapi, but it's never been enabled by default for me on windows.  I will try creating a m2 settings

**Comment by superstrom** [comment]
Thanks, after creating an .m2/settings.xml containing a profile with those properties, SunMSCAPI worked like a charm.

**Comment by andyolivares** [comment]
I'm facing the same problem. I have a company certificate chain using ZScaler.
Can you please post an example settings.xml with your solution?
