### ISSUE TITLE
How to set the repository address to local

### ISSUE THREAD

**Issue by bxjg1987** [ikvmnet/ikvm-maven#65]
First of all, thank you very much for this library, it's very cool!

IKVM.Maven.Sdk 1.6.9

my maven setting.xml ：
D:\apache-maven-3.9.8\mvn_repo

How to set up ikvm to use my local repository

**Comment by wasabii** [comment]
https://github.com/ikvmnet/ikvm-maven/issues/39#issuecomment-1795591169

**Comment by bxjg1987** [comment]
thanks!
