### ISSUE TITLE
Generated assembly Patch version always zero

### ISSUE THREAD

**Issue by joniles** [ikvmnet/ikvm-maven#69]
I'm including a jar into my project using `IKVM.Maven.Sdk` like this:

```xml
<ItemGroup>
  <PackageReference Include="IKVM.Maven.Sdk" Version="1.8.0" />
  <MavenReference Include="net.sf.mpxj:mpxj" Version="13.2.1" />
</ItemGroup>
```

After building the project it appears that the IKVM generated `mpxj.dll` assembly has the version `13.2.0`. Similarly if I look at one of the dependencies of this jar, for example jsoup, the dependency version in the MPXJ POM is `1.15.3`, but the IKVM generated `org.jsoup.dll` has the version `1.15.0`. 

I've checked the version by looking at the DLL File->Properties->Details in Windows Explorer, and also by decompiling using ILSpy. ILSpy indicates that both the FileVersion and the AssemblyFileVersion attributes appear with the patch version set to zero.

I wasn't sure if this was a deliberate design decision or if this is a genuine issue? Thanks!

**Comment by wasabii** [comment]
It was intentional. Doesn't matter for Core, but for Framework assemblies since they bind by full name, we don't want it too specific. 

It's also not derived from the POM, but from the version in the module, or from the file name, as defined by the automatic module name specification.

**Comment by joniles** [comment]
Thanks for the response! Quick followup question:

The context for this is the `MPXJ.Net` package, which is a .Net wrapper around the IKVM-translated Java version of MPXJ.

I'm aware that IKVM.Maven.Sdk caches build results. If a user builds their project with MPXJ.Net 13.2.0 (which specifies the dependency on MPXJ as  `<MavenReference Include="net.sf.mpxj:mpxj" Version="13.2.0" />`), and then later updates to MPXJ.Net 13.2.1 (with the dependency on MPXJ specified as `<MavenReference Include="net.sf.mpxj:mpxj" Version="13.2.1" />`), should I be concerned about the user receiving the correct translated version of MPXJ, as both assemblies generated by IKVM.Maven.Sdk  will have the version 13.2.0?

**Comment by wasabii** [comment]
The version of the assembly only matters to .Net Framework assembly binding. So, no. Nothing to do with how it is generated, how it gets there, how it is cashed, etc.

**Comment by joniles** [comment]
Thanks for the clarification!
