### ISSUE TITLE
Can not get namespaces from MavenReference org.mustangproject:validator

### ISSUE THREAD

**Issue by DavidBal** [ikvmnet/ikvm-maven#70]
Hi,

i am strugling to get this work with the `org.mustangproject:validator` project.

Here is my csproj file:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Image.JDK" Version="8.10.1" />
    <PackageReference Include="IKVM.Image.JRE" Version="8.10.1" />
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.8.2" />
  </ItemGroup>

	<ItemGroup>
		<MavenReference Include="org.mustangproject:validator" Version="2.13.0" />
	</ItemGroup>

</Project>
```

The `org.mustangproject:validator` project should have a namespace/package `org.mustangproject.validator` but that is not shown to me.

There is no error message at buildtime.

Do you have any advice for me on this matter?

Thanks in advance.

Kind regards,
David

**Comment by wasabii** [comment]
warning :     (class format error "55.0") is output for most of the class files. So I'm pretty sure this is beyond JDK8.

**Comment by DavidBal** [comment]
Hi,

thanks for the quick answer.

Kind regards,

David
