### ISSUE TITLE
IKVM.Maven.Sdk.targets(37,64): error MSB4057: 该项目中不存在目标“ResolvePackageAssets”。

### ISSUE THREAD

**Issue by daviduuang** [ikvmnet/ikvm-maven#71]
Error occured when try to build project.

Test project attached.('packages' folder not contained due to large size.)

[WindowsFormsApp2.zip](https://github.com/user-attachments/files/17083429/WindowsFormsApp2.zip)

**Comment by wasabii** [comment]
Sorry, some description and english please.
